title: Mattress Firm Status Page
languageCode: en
params:
  copyrightHolder: Mattress Firm
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: ''
  description_header: |-
    This is a status page.
    MFRM
  eventsPerPage: 10
  groups:
    - ''
  logo: ''
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Our company public facing website
      link: 'https://mattressfirm.com'
      name: Website
    - description: The Hive
      link: 'https://mattressfirm.cherwellondemand.com/CherwellPortal/The MFRM Hive#0'
      name: The Hive
    - description: The Pulse
      name: Reports
    - description: HR
      name: Workday
    - link: outlook.office.com
      name: Emails
    - name: AX
  timezoneString: ' UTC'
